### ISSUE TITLE
Link for parts and assembly process

### ISSUE THREAD

**Issue by Utopiah** [willie-winkler/EXIT-SUIT#3]
Hi, I couldn't find a description with a bill of materials and laser cut patterns or 3D printable models on how to build this.

**Comment by willie-winkler** [comment]
Hello Fabien,
We've been jolted into action since Thrill's video three weeks ago. All of
a sudden we had the community we've been talking about building and lots of
people wanting plans for the suit straight away.
We're decided to run a test round of open-source production. We don't want
to do a general release and have lots of people confused, or building poor
quality or unfinished suits. I'll cause chaos. We're going to be selecting
these first makers soon in a system called Golden Tickets. You'll need to
leave your contact details on exitsuit.com to be selected for a Golden
Ticket.
Following the round of Golden Ticket production the design will become more
easily downloaded and made by everyone.
What sort of  making experience do you have? Got your own workshop?
Willie

**Comment by Utopiah** [comment]
Hey Willie, thanks for the prompt reply and kudos on the cool project.

I'm a maker but mostly working on open-source software for explorations, including design in VR of assets but of code of the solution itself too. You can see the code in https://git.benetou.fr/utopiah/text-code-xr-engine/ and numerous examples on e.g https://twitter.com/utopiah/status/1645126280726167554

I do have a small workshop with 3D printers and laser cuter but that's not my main focus. Yet, I find the intersection of both to be powerful.

I do think it's important for emerging technologies, being VR or otherwise, to be understood by society at large in order to become both useful and empowering, not black boxes to be trapped inside of. This is why I asked for files right now even though, to be perfectly frank with you, I might not implement and build right away. I asked more from a philosophical standpoint than a pragmatic one. I also supported quite a few project on CrowdSupply focusing on open-source hardware and I believe being open from the start works. That being said I do not know your project and community as you do so I wouldn't make any suggestion. I do hope you will manage the chaos to make this endeavor grow the way you believe is most positive.

**Comment by willie-winkler** [comment]
Thanks Fabien, We're committed to making this open-source and community
based. It sounds like you've got lots to bring to the party so I look
forward to your input.

**Comment by wScanlon** [comment]
Hey Willie, are you still actively developing this project? Sad to see no commits in months. Im a CNC owner/enthusiast and programer by profession would love to play with this.

**Comment by ZoliSoft** [comment]
Vr enthusiast, 3d printer user with woodshop and cnc access here. Would love to give this a go. Willie, when you are ready, so are we.

**Comment by willie-winkler** [comment]
Hello Fabien,

Yes, the project is still thundering on.

There are not any BOM or cutting path files available quite yet. We're
gonna launch all this stuff in a couple of months in Jan. There'll be much
better instructional videos and stuff by then too.

Willie

**Comment by taswin** [comment]
The files were publicly released today.

**Comment by Utopiah** [comment]
Wonderful! And for others interesting note also https://github.com/willie-winkler/EXIT-SUIT/releases/tag/v13.0 with .dxf and Gerber files.
